/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    FHEFoodVote: {
      address: "0x3579AbcC902c5e59B89ba46d5abc31d765fD95BE",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "voter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "country",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "foodId",
              type: "uint256",
            },
          ],
          name: "FoodVoted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "country",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "foodId",
              type: "uint256",
            },
          ],
          name: "getEncryptedVotes",
          outputs: [
            {
              internalType: "euint32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "hasVoted",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "country",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "foodId",
              type: "uint256",
            },
            {
              internalType: "externalEuint32",
              name: "encryptedVote",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proof",
              type: "bytes",
            },
          ],
          name: "vote",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9368216,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
